### ISSUE TITLE
Update dependencies for v0.3.0 release

### ISSUE THREAD

**Issue by tomvothecoder** [conda-forge/xcdat-feedstock#2]
Related to 
- `esmpy`, `xesmf` (https://github.com/XCDAT/xcdat/pull/164)
- `cftime`
- `python>=3.8`

We might need to include `numba` per https://github.com/pangeo-data/xESMF/issues/170

**Comment by chengzhuzhang** [comment]
Hey Tom, since we are so close to the next release. Can you consider to merge this PR, for facilitate testing?

**Comment by chengzhuzhang** [comment]
Hey Tom, Sorry about the confusion. I meant to comment here: https://github.com/xCDAT/xcdat_test/issues/35
In any case, I have a working version of xcdat_test env, so its all good.
